pipeline {
    agent any

    environment {
        IMAGE_NAME = "klibimayssa/my-spring-app"
        IMAGE_TAG = "1.0"
    }

    stages {
        stage('Build with Maven') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-17'
                    reuseNode true
                }
            }
            steps {
                dir('student-management') {
                    sh 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            agent any
            steps {
                dir('student-management') {
                    script {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh """
                            echo "$PASS" | docker login -u "$USER" --password-stdin
                            docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }
}
