pipeline {
    agent any

    environment {
        IMAGE_NAME = "klibimayssa/my-spring-app"
        IMAGE_TAG = "1.0"
    }

    stages {
        stage('Build Maven') {
            steps {
                dir('student-management') {  // ← AJOUTEZ CE BLOC
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('student-management') {  // ← AJOUTEZ CE BLOC
                    script {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
    }
}