pipeline {
    agent any

    stages {
        stage('Build with Maven') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-17'
                    reuseNode true      // very important on Windows/Mac
                }
            }
            steps {
                checkout scm                     // <-- Jenkins does the git checkout on the host
                dir('student-management') {
                    sh 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            agent any
            steps {
                dir('student-management') {
                    script {
                        def image = docker.build("klibimayssa/my-spring-app:1.0.${env.BUILD_NUMBER}")

                        docker.withRegistry('', 'dockerhub-cred') {
                            image.push()
                            image.push('latest')
                        }
                    }
                }
            }
        }
    }
}